version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "${PORT}:6000"
    networks:
      - nest
  mongo:
    image: mongo
    networks:
      - nest
    environment:
      - MONGO_INITDB_DATABASE=demo
networks:
  nest:
    driver: bridge
