version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - nest
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - nest
    environment:
      - MONGO_INITDB_DATABASE=demo
networks:
  nest:
    driver: bridge